const enrollments = [
  {
    "enrollment_id":1,
    "student_id":12,
    "course_id":6,
    "grade":"D"
  },
  {
    "enrollment_id":2,
    "student_id":55,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":3,
    "student_id":13,
    "course_id":4,
    "grade":"F"
  },
  {
    "enrollment_id":4,
    "student_id":23,
    "course_id":8,
    "grade":"B"
  },
  {
    "enrollment_id":5,
    "student_id":89,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":6,
    "student_id":99,
    "course_id":8,
    "grade":"C"
  },
  {
    "enrollment_id":7,
    "student_id":30,
    "course_id":9,
    "grade":"D"
  },
  {
    "enrollment_id":8,
    "student_id":17,
    "course_id":3,
    "grade":"A"
  },
  {
    "enrollment_id":9,
    "student_id":62,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":10,
    "student_id":84,
    "course_id":2,
    "grade":"C"
  },
  {
    "enrollment_id":11,
    "student_id":89,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":12,
    "student_id":86,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":13,
    "student_id":13,
    "course_id":3,
    "grade":"C"
  },
  {
    "enrollment_id":14,
    "student_id":59,
    "course_id":5,
    "grade":"B"
  },
  {
    "enrollment_id":15,
    "student_id":19,
    "course_id":5,
    "grade":"C"
  },
  {
    "enrollment_id":16,
    "student_id":49,
    "course_id":2,
    "grade":"A"
  },
  {
    "enrollment_id":17,
    "student_id":100,
    "course_id":10,
    "grade":"C"
  },
  {
    "enrollment_id":18,
    "student_id":12,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":19,
    "student_id":61,
    "course_id":5,
    "grade":"D"
  },
  {
    "enrollment_id":20,
    "student_id":19,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":21,
    "student_id":76,
    "course_id":1,
    "grade":"C"
  },
  {
    "enrollment_id":22,
    "student_id":9,
    "course_id":5,
    "grade":"A"
  },
  {
    "enrollment_id":23,
    "student_id":71,
    "course_id":9,
    "grade":"D"
  },
  {
    "enrollment_id":24,
    "student_id":28,
    "course_id":10,
    "grade":"F"
  },
  {
    "enrollment_id":25,
    "student_id":78,
    "course_id":2,
    "grade":"A"
  },
  {
    "enrollment_id":26,
    "student_id":95,
    "course_id":1,
    "grade":"A"
  },
  {
    "enrollment_id":27,
    "student_id":52,
    "course_id":10,
    "grade":"F"
  },
  {
    "enrollment_id":28,
    "student_id":83,
    "course_id":9,
    "grade":"C"
  },
  {
    "enrollment_id":29,
    "student_id":16,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":30,
    "student_id":69,
    "course_id":9,
    "grade":"D"
  },
  {
    "enrollment_id":31,
    "student_id":99,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":32,
    "student_id":12,
    "course_id":6,
    "grade":"F"
  },
  {
    "enrollment_id":33,
    "student_id":25,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":34,
    "student_id":52,
    "course_id":1,
    "grade":"A"
  },
  {
    "enrollment_id":35,
    "student_id":85,
    "course_id":10,
    "grade":"D"
  },
  {
    "enrollment_id":36,
    "student_id":100,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":37,
    "student_id":53,
    "course_id":1,
    "grade":"A"
  },
  {
    "enrollment_id":38,
    "student_id":23,
    "course_id":8,
    "grade":"D"
  },
  {
    "enrollment_id":39,
    "student_id":16,
    "course_id":1,
    "grade":"D"
  },
  {
    "enrollment_id":40,
    "student_id":57,
    "course_id":3,
    "grade":"F"
  },
  {
    "enrollment_id":41,
    "student_id":39,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":42,
    "student_id":53,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":43,
    "student_id":42,
    "course_id":6,
    "grade":"F"
  },
  {
    "enrollment_id":44,
    "student_id":58,
    "course_id":10,
    "grade":"C"
  },
  {
    "enrollment_id":45,
    "student_id":39,
    "course_id":7,
    "grade":"C"
  },
  {
    "enrollment_id":46,
    "student_id":14,
    "course_id":8,
    "grade":"C"
  },
  {
    "enrollment_id":47,
    "student_id":95,
    "course_id":2,
    "grade":"F"
  },
  {
    "enrollment_id":48,
    "student_id":5,
    "course_id":10,
    "grade":"A"
  },
  {
    "enrollment_id":49,
    "student_id":35,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":50,
    "student_id":87,
    "course_id":3,
    "grade":"F"
  },
  {
    "enrollment_id":51,
    "student_id":93,
    "course_id":7,
    "grade":"C"
  },
  {
    "enrollment_id":52,
    "student_id":75,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":53,
    "student_id":18,
    "course_id":7,
    "grade":"A"
  },
  {
    "enrollment_id":54,
    "student_id":76,
    "course_id":2,
    "grade":"C"
  },
  {
    "enrollment_id":55,
    "student_id":9,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":56,
    "student_id":74,
    "course_id":6,
    "grade":"B"
  },
  {
    "enrollment_id":57,
    "student_id":58,
    "course_id":3,
    "grade":"D"
  },
  {
    "enrollment_id":58,
    "student_id":17,
    "course_id":3,
    "grade":"A"
  },
  {
    "enrollment_id":59,
    "student_id":7,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":60,
    "student_id":46,
    "course_id":7,
    "grade":"C"
  },
  {
    "enrollment_id":61,
    "student_id":13,
    "course_id":5,
    "grade":"D"
  },
  {
    "enrollment_id":62,
    "student_id":40,
    "course_id":10,
    "grade":"A"
  },
  {
    "enrollment_id":63,
    "student_id":42,
    "course_id":7,
    "grade":"F"
  },
  {
    "enrollment_id":64,
    "student_id":9,
    "course_id":9,
    "grade":"C"
  },
  {
    "enrollment_id":65,
    "student_id":50,
    "course_id":1,
    "grade":"B"
  },
  {
    "enrollment_id":66,
    "student_id":27,
    "course_id":7,
    "grade":"B"
  },
  {
    "enrollment_id":67,
    "student_id":66,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":68,
    "student_id":5,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":69,
    "student_id":29,
    "course_id":9,
    "grade":"D"
  },
  {
    "enrollment_id":70,
    "student_id":37,
    "course_id":1,
    "grade":"A"
  },
  {
    "enrollment_id":71,
    "student_id":38,
    "course_id":4,
    "grade":"D"
  },
  {
    "enrollment_id":72,
    "student_id":83,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":73,
    "student_id":8,
    "course_id":4,
    "grade":"F"
  },
  {
    "enrollment_id":74,
    "student_id":65,
    "course_id":10,
    "grade":"A"
  },
  {
    "enrollment_id":75,
    "student_id":86,
    "course_id":3,
    "grade":"A"
  },
  {
    "enrollment_id":76,
    "student_id":17,
    "course_id":9,
    "grade":"C"
  },
  {
    "enrollment_id":77,
    "student_id":71,
    "course_id":2,
    "grade":"C"
  },
  {
    "enrollment_id":78,
    "student_id":89,
    "course_id":4,
    "grade":"F"
  },
  {
    "enrollment_id":79,
    "student_id":45,
    "course_id":6,
    "grade":"A"
  },
  {
    "enrollment_id":80,
    "student_id":4,
    "course_id":2,
    "grade":"F"
  },
  {
    "enrollment_id":81,
    "student_id":36,
    "course_id":8,
    "grade":"C"
  },
  {
    "enrollment_id":82,
    "student_id":70,
    "course_id":8,
    "grade":"C"
  },
  {
    "enrollment_id":83,
    "student_id":31,
    "course_id":1,
    "grade":"A"
  },
  {
    "enrollment_id":84,
    "student_id":19,
    "course_id":3,
    "grade":"D"
  },
  {
    "enrollment_id":85,
    "student_id":61,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":86,
    "student_id":54,
    "course_id":9,
    "grade":"C"
  },
  {
    "enrollment_id":87,
    "student_id":39,
    "course_id":5,
    "grade":"C"
  },
  {
    "enrollment_id":88,
    "student_id":91,
    "course_id":6,
    "grade":"D"
  },
  {
    "enrollment_id":89,
    "student_id":74,
    "course_id":4,
    "grade":"D"
  },
  {
    "enrollment_id":90,
    "student_id":90,
    "course_id":10,
    "grade":"F"
  },
  {
    "enrollment_id":91,
    "student_id":19,
    "course_id":2,
    "grade":"F"
  },
  {
    "enrollment_id":92,
    "student_id":39,
    "course_id":8,
    "grade":"B"
  },
  {
    "enrollment_id":93,
    "student_id":67,
    "course_id":6,
    "grade":"B"
  },
  {
    "enrollment_id":94,
    "student_id":45,
    "course_id":5,
    "grade":"A"
  },
  {
    "enrollment_id":95,
    "student_id":13,
    "course_id":9,
    "grade":"F"
  },
  {
    "enrollment_id":96,
    "student_id":92,
    "course_id":1,
    "grade":"C"
  },
  {
    "enrollment_id":97,
    "student_id":58,
    "course_id":5,
    "grade":"F"
  },
  {
    "enrollment_id":98,
    "student_id":20,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":99,
    "student_id":92,
    "course_id":5,
    "grade":"D"
  },
  {
    "enrollment_id":100,
    "student_id":72,
    "course_id":6,
    "grade":"F"
  },
  {
    "enrollment_id":101,
    "student_id":61,
    "course_id":6,
    "grade":"D"
  },
  {
    "enrollment_id":102,
    "student_id":39,
    "course_id":7,
    "grade":"B"
  },
  {
    "enrollment_id":103,
    "student_id":1,
    "course_id":4,
    "grade":"B"
  },
  {
    "enrollment_id":104,
    "student_id":3,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":105,
    "student_id":77,
    "course_id":7,
    "grade":"F"
  },
  {
    "enrollment_id":106,
    "student_id":92,
    "course_id":9,
    "grade":"D"
  },
  {
    "enrollment_id":107,
    "student_id":62,
    "course_id":7,
    "grade":"C"
  },
  {
    "enrollment_id":108,
    "student_id":63,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":109,
    "student_id":25,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":110,
    "student_id":56,
    "course_id":8,
    "grade":"C"
  },
  {
    "enrollment_id":111,
    "student_id":33,
    "course_id":5,
    "grade":"D"
  },
  {
    "enrollment_id":112,
    "student_id":38,
    "course_id":4,
    "grade":"D"
  },
  {
    "enrollment_id":113,
    "student_id":6,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":114,
    "student_id":58,
    "course_id":6,
    "grade":"F"
  },
  {
    "enrollment_id":115,
    "student_id":44,
    "course_id":2,
    "grade":"A"
  },
  {
    "enrollment_id":116,
    "student_id":45,
    "course_id":4,
    "grade":"B"
  },
  {
    "enrollment_id":117,
    "student_id":32,
    "course_id":4,
    "grade":"F"
  },
  {
    "enrollment_id":118,
    "student_id":45,
    "course_id":6,
    "grade":"D"
  },
  {
    "enrollment_id":119,
    "student_id":61,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":120,
    "student_id":47,
    "course_id":1,
    "grade":"D"
  },
  {
    "enrollment_id":121,
    "student_id":21,
    "course_id":8,
    "grade":"B"
  },
  {
    "enrollment_id":122,
    "student_id":80,
    "course_id":6,
    "grade":"D"
  },
  {
    "enrollment_id":123,
    "student_id":85,
    "course_id":3,
    "grade":"A"
  },
  {
    "enrollment_id":124,
    "student_id":75,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":125,
    "student_id":36,
    "course_id":2,
    "grade":"C"
  },
  {
    "enrollment_id":126,
    "student_id":99,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":127,
    "student_id":19,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":128,
    "student_id":20,
    "course_id":3,
    "grade":"C"
  },
  {
    "enrollment_id":129,
    "student_id":57,
    "course_id":5,
    "grade":"A"
  },
  {
    "enrollment_id":130,
    "student_id":18,
    "course_id":6,
    "grade":"A"
  },
  {
    "enrollment_id":131,
    "student_id":47,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":132,
    "student_id":49,
    "course_id":6,
    "grade":"F"
  },
  {
    "enrollment_id":133,
    "student_id":14,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":134,
    "student_id":15,
    "course_id":3,
    "grade":"A"
  },
  {
    "enrollment_id":135,
    "student_id":31,
    "course_id":4,
    "grade":"C"
  },
  {
    "enrollment_id":136,
    "student_id":1,
    "course_id":1,
    "grade":"D"
  },
  {
    "enrollment_id":137,
    "student_id":54,
    "course_id":4,
    "grade":"B"
  },
  {
    "enrollment_id":138,
    "student_id":3,
    "course_id":1,
    "grade":"B"
  },
  {
    "enrollment_id":139,
    "student_id":16,
    "course_id":1,
    "grade":"F"
  },
  {
    "enrollment_id":140,
    "student_id":87,
    "course_id":10,
    "grade":"F"
  },
  {
    "enrollment_id":141,
    "student_id":57,
    "course_id":6,
    "grade":"B"
  },
  {
    "enrollment_id":142,
    "student_id":75,
    "course_id":5,
    "grade":"F"
  },
  {
    "enrollment_id":143,
    "student_id":12,
    "course_id":4,
    "grade":"C"
  },
  {
    "enrollment_id":144,
    "student_id":74,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":145,
    "student_id":96,
    "course_id":1,
    "grade":"F"
  },
  {
    "enrollment_id":146,
    "student_id":16,
    "course_id":6,
    "grade":"B"
  },
  {
    "enrollment_id":147,
    "student_id":72,
    "course_id":2,
    "grade":"D"
  },
  {
    "enrollment_id":148,
    "student_id":76,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":149,
    "student_id":24,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":150,
    "student_id":28,
    "course_id":5,
    "grade":"A"
  },
  {
    "enrollment_id":151,
    "student_id":8,
    "course_id":7,
    "grade":"F"
  },
  {
    "enrollment_id":152,
    "student_id":92,
    "course_id":10,
    "grade":"A"
  },
  {
    "enrollment_id":153,
    "student_id":36,
    "course_id":2,
    "grade":"B"
  },
  {
    "enrollment_id":154,
    "student_id":90,
    "course_id":8,
    "grade":"D"
  },
  {
    "enrollment_id":155,
    "student_id":8,
    "course_id":2,
    "grade":"F"
  },
  {
    "enrollment_id":156,
    "student_id":58,
    "course_id":4,
    "grade":"B"
  },
  {
    "enrollment_id":157,
    "student_id":60,
    "course_id":1,
    "grade":"F"
  },
  {
    "enrollment_id":158,
    "student_id":50,
    "course_id":5,
    "grade":"C"
  },
  {
    "enrollment_id":159,
    "student_id":28,
    "course_id":9,
    "grade":"A"
  },
  {
    "enrollment_id":160,
    "student_id":92,
    "course_id":1,
    "grade":"C"
  },
  {
    "enrollment_id":161,
    "student_id":41,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":162,
    "student_id":100,
    "course_id":8,
    "grade":"D"
  },
  {
    "enrollment_id":163,
    "student_id":64,
    "course_id":6,
    "grade":"F"
  },
  {
    "enrollment_id":164,
    "student_id":27,
    "course_id":7,
    "grade":"A"
  },
  {
    "enrollment_id":165,
    "student_id":63,
    "course_id":3,
    "grade":"F"
  },
  {
    "enrollment_id":166,
    "student_id":17,
    "course_id":1,
    "grade":"B"
  },
  {
    "enrollment_id":167,
    "student_id":73,
    "course_id":5,
    "grade":"F"
  },
  {
    "enrollment_id":168,
    "student_id":33,
    "course_id":2,
    "grade":"A"
  },
  {
    "enrollment_id":169,
    "student_id":84,
    "course_id":5,
    "grade":"B"
  },
  {
    "enrollment_id":170,
    "student_id":77,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":171,
    "student_id":92,
    "course_id":9,
    "grade":"D"
  },
  {
    "enrollment_id":172,
    "student_id":29,
    "course_id":2,
    "grade":"B"
  },
  {
    "enrollment_id":173,
    "student_id":13,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":174,
    "student_id":46,
    "course_id":3,
    "grade":"D"
  },
  {
    "enrollment_id":175,
    "student_id":35,
    "course_id":1,
    "grade":"C"
  },
  {
    "enrollment_id":176,
    "student_id":6,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":177,
    "student_id":82,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":178,
    "student_id":69,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":179,
    "student_id":47,
    "course_id":9,
    "grade":"D"
  },
  {
    "enrollment_id":180,
    "student_id":25,
    "course_id":5,
    "grade":"C"
  },
  {
    "enrollment_id":181,
    "student_id":66,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":182,
    "student_id":10,
    "course_id":5,
    "grade":"F"
  },
  {
    "enrollment_id":183,
    "student_id":56,
    "course_id":5,
    "grade":"F"
  },
  {
    "enrollment_id":184,
    "student_id":30,
    "course_id":5,
    "grade":"C"
  },
  {
    "enrollment_id":185,
    "student_id":5,
    "course_id":3,
    "grade":"C"
  },
  {
    "enrollment_id":186,
    "student_id":33,
    "course_id":10,
    "grade":"D"
  },
  {
    "enrollment_id":187,
    "student_id":65,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":188,
    "student_id":18,
    "course_id":9,
    "grade":"C"
  },
  {
    "enrollment_id":189,
    "student_id":96,
    "course_id":10,
    "grade":"C"
  },
  {
    "enrollment_id":190,
    "student_id":49,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":191,
    "student_id":11,
    "course_id":2,
    "grade":"F"
  },
  {
    "enrollment_id":192,
    "student_id":85,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":193,
    "student_id":26,
    "course_id":8,
    "grade":"B"
  },
  {
    "enrollment_id":194,
    "student_id":63,
    "course_id":7,
    "grade":"D"
  },
  {
    "enrollment_id":195,
    "student_id":89,
    "course_id":8,
    "grade":"D"
  },
  {
    "enrollment_id":196,
    "student_id":86,
    "course_id":3,
    "grade":"C"
  },
  {
    "enrollment_id":197,
    "student_id":59,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":198,
    "student_id":27,
    "course_id":1,
    "grade":"D"
  },
  {
    "enrollment_id":199,
    "student_id":49,
    "course_id":7,
    "grade":"C"
  },
  {
    "enrollment_id":200,
    "student_id":77,
    "course_id":1,
    "grade":"A"
  },
  {
    "enrollment_id":201,
    "student_id":33,
    "course_id":9,
    "grade":"C"
  },
  {
    "enrollment_id":202,
    "student_id":98,
    "course_id":1,
    "grade":"F"
  },
  {
    "enrollment_id":203,
    "student_id":99,
    "course_id":1,
    "grade":"C"
  },
  {
    "enrollment_id":204,
    "student_id":1,
    "course_id":7,
    "grade":"B"
  },
  {
    "enrollment_id":205,
    "student_id":21,
    "course_id":2,
    "grade":"A"
  },
  {
    "enrollment_id":206,
    "student_id":55,
    "course_id":5,
    "grade":"B"
  },
  {
    "enrollment_id":207,
    "student_id":6,
    "course_id":8,
    "grade":"B"
  },
  {
    "enrollment_id":208,
    "student_id":92,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":209,
    "student_id":81,
    "course_id":3,
    "grade":"A"
  },
  {
    "enrollment_id":210,
    "student_id":69,
    "course_id":7,
    "grade":"A"
  },
  {
    "enrollment_id":211,
    "student_id":95,
    "course_id":3,
    "grade":"A"
  },
  {
    "enrollment_id":212,
    "student_id":5,
    "course_id":6,
    "grade":"A"
  },
  {
    "enrollment_id":213,
    "student_id":3,
    "course_id":6,
    "grade":"A"
  },
  {
    "enrollment_id":214,
    "student_id":53,
    "course_id":3,
    "grade":"F"
  },
  {
    "enrollment_id":215,
    "student_id":23,
    "course_id":7,
    "grade":"C"
  },
  {
    "enrollment_id":216,
    "student_id":53,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":217,
    "student_id":37,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":218,
    "student_id":74,
    "course_id":10,
    "grade":"C"
  },
  {
    "enrollment_id":219,
    "student_id":74,
    "course_id":4,
    "grade":"C"
  },
  {
    "enrollment_id":220,
    "student_id":83,
    "course_id":1,
    "grade":"B"
  },
  {
    "enrollment_id":221,
    "student_id":17,
    "course_id":4,
    "grade":"F"
  },
  {
    "enrollment_id":222,
    "student_id":85,
    "course_id":7,
    "grade":"D"
  },
  {
    "enrollment_id":223,
    "student_id":78,
    "course_id":4,
    "grade":"D"
  },
  {
    "enrollment_id":224,
    "student_id":73,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":225,
    "student_id":1,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":226,
    "student_id":51,
    "course_id":1,
    "grade":"D"
  },
  {
    "enrollment_id":227,
    "student_id":45,
    "course_id":5,
    "grade":"C"
  },
  {
    "enrollment_id":228,
    "student_id":77,
    "course_id":7,
    "grade":"F"
  },
  {
    "enrollment_id":229,
    "student_id":4,
    "course_id":1,
    "grade":"D"
  },
  {
    "enrollment_id":230,
    "student_id":62,
    "course_id":4,
    "grade":"C"
  },
  {
    "enrollment_id":231,
    "student_id":65,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":232,
    "student_id":32,
    "course_id":2,
    "grade":"A"
  },
  {
    "enrollment_id":233,
    "student_id":34,
    "course_id":10,
    "grade":"F"
  },
  {
    "enrollment_id":234,
    "student_id":92,
    "course_id":5,
    "grade":"A"
  },
  {
    "enrollment_id":235,
    "student_id":95,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":236,
    "student_id":72,
    "course_id":1,
    "grade":"A"
  },
  {
    "enrollment_id":237,
    "student_id":39,
    "course_id":6,
    "grade":"A"
  },
  {
    "enrollment_id":238,
    "student_id":26,
    "course_id":6,
    "grade":"D"
  },
  {
    "enrollment_id":239,
    "student_id":34,
    "course_id":4,
    "grade":"C"
  },
  {
    "enrollment_id":240,
    "student_id":54,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":241,
    "student_id":3,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":242,
    "student_id":50,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":243,
    "student_id":12,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":244,
    "student_id":65,
    "course_id":5,
    "grade":"B"
  },
  {
    "enrollment_id":245,
    "student_id":54,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":246,
    "student_id":5,
    "course_id":2,
    "grade":"D"
  },
  {
    "enrollment_id":247,
    "student_id":94,
    "course_id":3,
    "grade":"C"
  },
  {
    "enrollment_id":248,
    "student_id":94,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":249,
    "student_id":57,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":250,
    "student_id":17,
    "course_id":4,
    "grade":"F"
  },
  {
    "enrollment_id":251,
    "student_id":47,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":252,
    "student_id":23,
    "course_id":5,
    "grade":"B"
  },
  {
    "enrollment_id":253,
    "student_id":79,
    "course_id":4,
    "grade":"A"
  },
  {
    "enrollment_id":254,
    "student_id":85,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":255,
    "student_id":14,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":256,
    "student_id":66,
    "course_id":6,
    "grade":"B"
  },
  {
    "enrollment_id":257,
    "student_id":75,
    "course_id":6,
    "grade":"F"
  },
  {
    "enrollment_id":258,
    "student_id":51,
    "course_id":8,
    "grade":"A"
  },
  {
    "enrollment_id":259,
    "student_id":38,
    "course_id":7,
    "grade":"C"
  },
  {
    "enrollment_id":260,
    "student_id":64,
    "course_id":10,
    "grade":"B"
  },
  {
    "enrollment_id":261,
    "student_id":98,
    "course_id":10,
    "grade":"C"
  },
  {
    "enrollment_id":262,
    "student_id":38,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":263,
    "student_id":50,
    "course_id":2,
    "grade":"B"
  },
  {
    "enrollment_id":264,
    "student_id":98,
    "course_id":9,
    "grade":"D"
  },
  {
    "enrollment_id":265,
    "student_id":82,
    "course_id":1,
    "grade":"C"
  },
  {
    "enrollment_id":266,
    "student_id":30,
    "course_id":8,
    "grade":"B"
  },
  {
    "enrollment_id":267,
    "student_id":79,
    "course_id":4,
    "grade":"C"
  },
  {
    "enrollment_id":268,
    "student_id":91,
    "course_id":4,
    "grade":"B"
  },
  {
    "enrollment_id":269,
    "student_id":51,
    "course_id":5,
    "grade":"A"
  },
  {
    "enrollment_id":270,
    "student_id":63,
    "course_id":8,
    "grade":"C"
  },
  {
    "enrollment_id":271,
    "student_id":98,
    "course_id":5,
    "grade":"D"
  },
  {
    "enrollment_id":272,
    "student_id":52,
    "course_id":8,
    "grade":"D"
  },
  {
    "enrollment_id":273,
    "student_id":38,
    "course_id":10,
    "grade":"F"
  },
  {
    "enrollment_id":274,
    "student_id":97,
    "course_id":1,
    "grade":"B"
  },
  {
    "enrollment_id":275,
    "student_id":88,
    "course_id":10,
    "grade":"C"
  },
  {
    "enrollment_id":276,
    "student_id":79,
    "course_id":9,
    "grade":"F"
  },
  {
    "enrollment_id":277,
    "student_id":30,
    "course_id":6,
    "grade":"C"
  },
  {
    "enrollment_id":278,
    "student_id":51,
    "course_id":3,
    "grade":"B"
  },
  {
    "enrollment_id":279,
    "student_id":81,
    "course_id":8,
    "grade":"D"
  },
  {
    "enrollment_id":280,
    "student_id":5,
    "course_id":9,
    "grade":"A"
  },
  {
    "enrollment_id":281,
    "student_id":29,
    "course_id":6,
    "grade":"D"
  },
  {
    "enrollment_id":282,
    "student_id":4,
    "course_id":7,
    "grade":"F"
  },
  {
    "enrollment_id":283,
    "student_id":10,
    "course_id":1,
    "grade":"A"
  },
  {
    "enrollment_id":284,
    "student_id":56,
    "course_id":5,
    "grade":"F"
  },
  {
    "enrollment_id":285,
    "student_id":17,
    "course_id":5,
    "grade":"B"
  },
  {
    "enrollment_id":286,
    "student_id":74,
    "course_id":10,
    "grade":"A"
  },
  {
    "enrollment_id":287,
    "student_id":17,
    "course_id":4,
    "grade":"F"
  },
  {
    "enrollment_id":288,
    "student_id":84,
    "course_id":6,
    "grade":"B"
  },
  {
    "enrollment_id":289,
    "student_id":88,
    "course_id":7,
    "grade":"D"
  },
  {
    "enrollment_id":290,
    "student_id":69,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":291,
    "student_id":34,
    "course_id":1,
    "grade":"C"
  },
  {
    "enrollment_id":292,
    "student_id":6,
    "course_id":6,
    "grade":"B"
  },
  {
    "enrollment_id":293,
    "student_id":53,
    "course_id":7,
    "grade":"B"
  },
  {
    "enrollment_id":294,
    "student_id":66,
    "course_id":3,
    "grade":"C"
  },
  {
    "enrollment_id":295,
    "student_id":77,
    "course_id":8,
    "grade":"F"
  },
  {
    "enrollment_id":296,
    "student_id":43,
    "course_id":5,
    "grade":"F"
  },
  {
    "enrollment_id":297,
    "student_id":75,
    "course_id":9,
    "grade":"B"
  },
  {
    "enrollment_id":298,
    "student_id":23,
    "course_id":5,
    "grade":"C"
  },
  {
    "enrollment_id":299,
    "student_id":55,
    "course_id":9,
    "grade":"C"
  },
  {
    "enrollment_id":300,
    "student_id":80,
    "course_id":10,
    "grade":"D"
  }
];

export default enrollments;
